### ISSUE TITLE
01Jul22 - Easee Cloud API update with backwards compatibility break (changed login URL)

### ISSUE THREAD

**Issue by hijacker123** [Newan/ioBroker.easee#47] opened 2022-06-14 07:57 UTC
Are you aware about this API login URL change ? Otherwise this easse-iobroker adapter might not work after July 1st, 2022.

[https://status.easee.com/](url) 

Can you please create an updated release ?

![easee_snip](https://user-images.githubusercontent.com/62598997/173524504-e7069b21-635c-48bf-be1e-f5cdc0d6af16.GIF)

**Comment by marwin79** [comment] 2022-06-14 08:20
Duplicate of #45

**Comment by marwin79** [comment] 2022-06-19 11:22
@Newan did you release the change in issue #45? Not so familiar with releases, but I think not. We should have a version 1.0.7 in ioBroker "stable" until July 1st. After that that it will no longer be working.

**Comment by Newan** [comment] 2022-06-19 15:25
It is in latest, not in stable.

Next week after holiday a can release it to stabel

**Comment by hijacker123** [comment] 2022-07-04 08:07
Today the easse login will be changed:

https://status.easee.com/

Please release as soon as possible a stable release(1.0.7 ?) that can be easily updated in iobroker. Latest available release in iobroker is currently 1.0.5

**Comment by marwin79** [comment] 2022-07-05 06:32
Looks like "token" still works. But if it should break before we have a fixed version release, just go to the file 
_iobroker_installation_/node_modules/iobroker.easee/main.js
and change
`            const response = await axios.post(apiUrl + '/api/accounts/token', {`
to
`            const response = await axios.post(apiUrl + '/api/accounts/login', {`

**Comment by hijacker123** [comment] 2022-07-06 07:52
Thanks a lot for quick reply, this will work as temporary workaround.

**Closed** 2023-02-26 06:48 UTC
