### ISSUE TITLE
Login failed since Easee-API update

### ISSUE THREAD

**Issue by Yopollo63** [Newan/ioBroker.easee#49] opened 2022-07-06 11:56 UTC
Easee will remove one of their login endpoints during this maintenance. If you have any systems relying on 'https://api.easee.cloud/api/accounts/token' please move this to 'https://api.easee.cloud/api/accounts/login' before this maintenance.

[https://easee.statuspage.io/incidents/zqqdv81f23sx](Link)

**Comment by Newan** [comment] 2022-07-06 18:37
Duplicate of https://github.com/Newan/ioBroker.easee/issues/45

**Closed by Newan** 2022-07-06 18:37 UTC
